### PR TITLE
fix polling logic on network errors #995

### LINKED ISSUE #995: Desktop client doesn't receive messages / port issue
Hi. First, I love the app very user-friendly, good job
Im running the appimage. I've run 1.0.4 and 1.0.5 (same sync issue with both version)
I have 1 client running on main and another client running in virtualbox
I often have to restart the receiver side client in order for the app to sync a new message sent from the other client. 
I've noticed that this sync issue occur when im not using the app for a period of time (idle) .
main run mx linux: OS: MX x86_64  Kernel: 4.19.0-6-amd64
vb run linuxlite: OS: Linux Lite 4.8 x86_64  Kernel: 4.15.0-91-generic
Thanks for session.

### PR DESCRIPTION
**Pull request by Bilb**
Not sure this completely resolve #995 yet, but it should help

### CODE REVIEW

File: ts/session/snode_api/swarmPolling.ts [hunk 1]
```diff
@@ -133,7 +131,7 @@ export class SwarmPolling {
 
     const lastMessage = _.last(messages);
 
-    this.updateLastHash(
+    void this.updateLastHash(
```
Comment (Mikunj) [inline ts/session/snode_api/swarmPolling.ts:134]: should we await this?

Comment (Bilb) [reply ts/session/snode_api/swarmPolling.ts:134]: fixed

**Review by Mikunj — APPROVED** [review]
