### PR TITLE
Check for model in blocked settings

### LINKED ISSUE #1311: Unblock Users Page in Settings is broken
**Describe the bug**

`Top-level unhandled error: TypeError: Cannot read property 'getProfileName' of undefined`
That is caused by line `607` in `SessionSettings.ts` which was changed in PR #1308

@Bilb That's because not every blocked SessionID has a UserModel

I'll Fix it real quick

**To Reproduce**
1. Block Contact
2. Delete Contact

**Screenshots or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Other information (please complete the following information):**

* Device: PC
* OS: Windows 10
* Session Version or Git commit hash:

### PR DESCRIPTION
**Pull request by konstantinullrich**
### Contributor checklist:

* [x] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [x] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [x] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [x] My changes are ready to be shipped to users

### Description
Fixes #1311 

It checks now for a Model. Because if I Block a User and then delete his Contact. The Blocked Session ID is stored but the model for that contact not.

### CODE REVIEW

File: ts/components/session/settings/SessionSettings.tsx [hunk 1]
```diff
@@ -622,7 +626,11 @@ export class SettingsView extends React.Component<SettingsViewProps, State> {
         },
         comparisonValue: undefined,
         setFn: async () => {
-          await currentModel.unblock();
+          if (currentModel) {
+            await currentModel.unblock();
+          } else {
+            await BlockedNumberController.unblock(blockedNumber);
+          }
```
Comment (Bilb) [inline ts/components/session/settings/SessionSettings.tsx:633]: The issue with this is that the UI won't refresh with an unblock from 
```
            await BlockedNumberController.unblock
```

We need to find a way to have it refreshed

Comment (konstantinullrich) [reply ts/components/session/settings/SessionSettings.tsx]: Done in the next Commit using "Component.forceUpdate"

**Review by Bilb — APPROVED** [review]
